<?php
include "include/functions.php";
if(isset($_GET["editor"])){$editor=xss_cleaner($_GET["editor"]);}
if(isset($_POST["comment"])){$comment=xss_cleaner(trim(rawurldecode($_POST["comment"])));}
else{?>
<html>
<head>
<title>Preview code..</title>
<script type="text/javascript">
function fw_trim(str){return str.replace(/^\s\s*/, '').replace(/\s\s*$/, '');}
function fw_connect(url,params){
var fw_connection;
try{fw_connection = new XMLHttpRequest();}
catch(e){
try{fw_connection = new ActiveXObject("Msxml2.XMLHTTP");}
catch (e){
try{fw_connection = new ActiveXObject("Microsoft.XMLHTTP");}
catch (e){return false;}}}
fw_connection.open("POST", url, true);
fw_connection.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
fw_connection.setRequestHeader("Content-length", params.length);
fw_connection.setRequestHeader("fw_connection", "close");
fw_connection.send(params);
return(fw_connection);}
function fw_total_encode(str){
var s=escape(fw_trim(str));
s=s.replace(/\+/g,"%2B");
s=s.replace(/@/g,"%40");
s=s.replace(/\//g,"%2F");
s=s.replace(/\*/g,"%2A");
return(s);}
if(null==(parent.opener)){window.close();}
function loadPreview(){
var fwParentID='<?php echo $editor;?>';
var w=window.opener.document.getElementById(fwParentID);
var url='preview.php';
var params = "comment=" +fw_total_encode(w.value);
if((window.opener.document.getElementById('fw_parseurls'))&&(window.opener.document.getElementById('fw_parseurls').checked)){params+='&autolink=true';}
var fw_connection=fw_connect(url,params);
fw_connection.onreadystatechange = function(){
if(fw_connection.readyState == 4){
if(fw_connection.status == 200){
var str='<p style="color:gray; margin-top:20px; font-size:10px;">-------------------------------------<br />Preview generated by <a href="http://ramui.com/">ramui.com</a></p>';
document.getElementById('preview').innerHTML = fw_connection.responseText+str;}}}
}
window.onload=loadPreview;
</script>
<style>
body, div{font:500 12px georgia;line-height:150%;}
div.fw_code_heading{font:600 13px arial;clear:both;margin-top:20px;}
.fw_code{border:1px solid #888;clear:both;background:#fff;font:500 15px 'courier new';}
.fw_code:hover{background:#f2f2f2;}
blockquote{margin:10px 5px;background:#f0f0f0;font:800 13px arial;color:#800000;border-left:3px solid #666;padding:1px 10px;}
</style>
</head><body style="margin:0;padding:0;background:#fff url('images/bg.gif') repeat-x;"><img src="images/caption.gif" width="205px" height="66px" style="clear:both;border:none; margin:0 20px; padding:0;" />
<div id="preview" style="clear:both;border:1px solid #d4d0c8;margin:10px; padding:5px;">
<div style="clear:both;text-align:center;margin:90px 0;"><img src="images/loder.gif" alt="Loding.." /></div>
</div></body></html>
<?php
exit;}
$comment=fw_strip_slashes($comment);
$autolink=isset($_POST['autolink']);
$bb= new bbcode(false);
echo $bb->format_text($comment,$autolink);
?>